[package]
name = "bevy_template"
version = "0.1.0"
authors = ["qomaeng <qomaeng@gmail.com>"]
edition = "2024"
license-file = "EULA"
publish = false

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.16.1"
