[graph]
all-features = true

[advisories]
ignore = [
  # paste was announced as unmaintained with no explanation or replacement
  # See: https://rustsec.org/advisories/RUSTSEC-2024-0436
  "RUSTSEC-2024-0436",
]

[licenses]
allow = [
  "0BSD",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "MIT-0",
  "Unlicense",
  "Zlib",
]
private = { ignore = true }
exceptions = [{ name = "unicode-ident", allow = ["Unicode-3.0"] }]

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
